# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_concat_interrupts_0/system_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_interrupts_0 || ORIG_REF_NAME==system_concat_interrupts_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_fclk1_0/system_proc_sys_reset_fclk1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_fclk1_0 || ORIG_REF_NAME==system_proc_sys_reset_fclk1_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_0/system_ps7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_0 || ORIG_REF_NAME==system_ps7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_fclk0_0/system_rst_ps7_0_fclk0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==system_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/system/ip/system_system_interrupts_0/system_system_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_system_interrupts_0 || ORIG_REF_NAME==system_system_interrupts_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_1/system_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_1 || ORIG_REF_NAME==system_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_1/system_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1 || ORIG_REF_NAME==system_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0/system_axi_vdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0 || ORIG_REF_NAME==system_axi_vdma_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_register_slice_0_1/system_axis_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_register_slice_0_1 || ORIG_REF_NAME==system_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_color_convert_1/system_color_convert_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_convert_1 || ORIG_REF_NAME==system_color_convert_1} -quiet] -quiet

# IP: bd/system/ip/system_pixel_unpack_0/system_pixel_unpack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_unpack_0 || ORIG_REF_NAME==system_pixel_unpack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dynclk_0/system_axi_dynclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0 || ORIG_REF_NAME==system_axi_dynclk_0} -quiet] -quiet

# IP: bd/system/ip/system_color_swap_0_1/system_color_swap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_swap_0_1 || ORIG_REF_NAME==system_color_swap_0_1} -quiet] -quiet

# IP: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0} -quiet] -quiet

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vtc_out_0/system_vtc_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vtc_out_0 || ORIG_REF_NAME==system_vtc_out_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_register_slice_0_0/system_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_register_slice_0_0 || ORIG_REF_NAME==system_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/system/ip/system_color_convert_0/system_color_convert_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_convert_0 || ORIG_REF_NAME==system_color_convert_0} -quiet] -quiet

# IP: bd/system/ip/system_pixel_pack_0/system_pixel_pack_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_pack_0 || ORIG_REF_NAME==system_pixel_pack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_hdmiin_0/system_axi_gpio_hdmiin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_hdmiin_0 || ORIG_REF_NAME==system_axi_gpio_hdmiin_0} -quiet] -quiet

# IP: bd/system/ip/system_color_swap_0_0/system_color_swap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_color_swap_0_0 || ORIG_REF_NAME==system_color_swap_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vtc_in_0/system_vtc_in_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_vtc_in_0 || ORIG_REF_NAME==system_vtc_in_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2} -quiet] -quiet

# IP: bd/system/ip/system_dvi2rgb_1_0/system_dvi2rgb_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dvi2rgb_1_0 || ORIG_REF_NAME==system_dvi2rgb_1_0} -quiet] -quiet

# IP: bd/system/ip/system_pixel_stream_0_0/system_pixel_stream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pixel_stream_0_0 || ORIG_REF_NAME==system_pixel_stream_0_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_1/system_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_1 || ORIG_REF_NAME==system_s00_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_1/system_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_1 || ORIG_REF_NAME==system_m00_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_1/system_m01_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_1 || ORIG_REF_NAME==system_m01_regslice_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_0 || ORIG_REF_NAME==system_m02_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1} -quiet] -quiet

# IP: bd/system/ip/system_m03_regslice_0/system_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m03_regslice_0 || ORIG_REF_NAME==system_m03_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m04_regslice_0/system_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m04_regslice_0 || ORIG_REF_NAME==system_m04_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m05_regslice_0/system_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m05_regslice_0 || ORIG_REF_NAME==system_m05_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m06_regslice_0/system_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m06_regslice_0 || ORIG_REF_NAME==system_m06_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_2/system_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2} -quiet] -quiet

# IP: bd/system/ip/system_m07_regslice_0/system_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m07_regslice_0 || ORIG_REF_NAME==system_m07_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_3/system_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_3 || ORIG_REF_NAME==system_auto_cc_3} -quiet] -quiet

# IP: bd/system/ip/system_m08_regslice_0/system_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m08_regslice_0 || ORIG_REF_NAME==system_m08_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m09_regslice_0/system_m09_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m09_regslice_0 || ORIG_REF_NAME==system_m09_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_2/system_s00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_2 || ORIG_REF_NAME==system_s00_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_s01_regslice_0/system_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s01_regslice_0 || ORIG_REF_NAME==system_s01_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_2/system_m00_regslice_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_2 || ORIG_REF_NAME==system_m00_regslice_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_0/system_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_0 || ORIG_REF_NAME==system_s00_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_0 || ORIG_REF_NAME==system_m00_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_0 || ORIG_REF_NAME==system_m01_regslice_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
