# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Work_Space/vivado_workspace/video_stream/video_stream.srcs/sources_1/bd/system/ip/system_m01_regslice_1/system_m01_regslice_1.xci
# IP: The module: 'system_m01_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Work_Space/vivado_workspace/video_stream/video_stream.srcs/sources_1/bd/system/ip/system_m01_regslice_1/system_m01_regslice_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_m01_regslice_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Work_Space/vivado_workspace/video_stream/video_stream.srcs/sources_1/bd/system/ip/system_m01_regslice_1/system_m01_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_m01_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Work_Space/vivado_workspace/video_stream/video_stream.srcs/sources_1/bd/system/ip/system_m01_regslice_1/system_m01_regslice_1.xci
# IP: The module: 'system_m01_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Work_Space/vivado_workspace/video_stream/video_stream.srcs/sources_1/bd/system/ip/system_m01_regslice_1/system_m01_regslice_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_m01_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Work_Space/vivado_workspace/video_stream/video_stream.srcs/sources_1/bd/system/ip/system_m01_regslice_1/system_m01_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_m01_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
